### playbook.yml
---
  - name: Install Docker and Docker Compose
    hosts: all
    become: true
    gather_facts: False
    # remote_user: ec2-user
    tasks:
      - name: Update yum package manager
        command: yum update -y
      - name: Install Docker
        command: yum install docker -y
      - name: Enable docker
        command: systemctl enable docker
      - name: Start docker
        command: systemctl start docker
      # this is a convienience for when we have to ssh into the nodes. 
      - name: Add sudo permissions for default ec2-user with docker
        command: sudo usermod -aG docker {{remote_user}}
  - name: Init Swarm Manager
    hosts: managers
    become: true
    gather_facts: False
    # remote_user: ec2-user
    tasks:
      - name: Swarm Init
        command: docker swarm init
      - name: Get Worker Token
        command: docker swarm join-token worker -q
        register: worker_token
      - name: Show Worker Token
        debug: var=worker_token.stdout
      - name: Manager Token
        command: docker swarm join-token manager -q
        register: manager_token
      - name: Show Manager Token
        debug: var=manager_token.stdout
  - name: Join Swarm Cluster
    hosts: workers
    become: true
    # remote_user: ec2-user
    gather_facts: False
    vars:
      token: "{{ hostvars[groups['managers'][0]]['worker_token']['stdout'] }}"
      manager: "{{ hostvars[groups['managers'][0]].manager_private_ip }}"
    tasks:
      - name: Join Swarm Cluster as a Worker
        command: docker swarm join --token {{ token }} {{ manager }}:2377
        register: worker
      - name: Show Results
        debug: var=worker.stdout
      - name: Show Errors
        debug: var=worker.stderr
  - name: Copy Docker Compose and Traefik config files
    hosts: managers
    become: true
    # remote_user: ec2-user
    tasks:
      - name: Copy files
        copy:
          src: ./assets/
          dest: /
  - name: Deploy stacks    
    hosts: managers
    become: true
    # remote_user: ec2-user
    tasks:
      - name: Deploy traefik stack
        command: sudo docker stack deploy -c /stack-traefik-main.yaml traefik
      - name: Deploy catnip stack
        command: sudo docker stack deploy -c /stack-canary.yaml catnip